# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Run Cypress Tests

on:
  pull_request:
    branches: ["angular/*"]

jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1
     
    steps:
      - name: Get Source
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 3.1.x

      - name: Test
        run: dotnet run --project build/Build.csproj --target=test

      - name: Summary
        run: |
          echo "# Bootstrap 3 Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Cypress not supported with Angular 10" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "# Bootstrap 4 Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Cypress not supported with Angular 10" >> $GITHUB_STEP_SUMMARY
          echo "# Bootstrap 5 Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Cypress not supported with Angular 10" >> $GITHUB_STEP_SUMMARY
